<a href="https://colab.research.google.com/github/Sarvesh7379/data-science/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas Series**
ASeries is a one_dimensional labaled array capable of holding any data type. the axis labels are collctive called the index.

In [4]:
import pandas as pd
import numpy as np

# **Creating**  **Series**
# THere are multiple ways to create a Pandas series

In [5]:
labels =['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30,])
d={1:10,2:30,3:40}

In [7]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(d)

1    10
2    30
3    40
dtype: int64

In [ ]:
#Data Frame

In [11]:
#Creating dataframe

In [12]:
data = {
    'Name':['Alice','Bob','Charlie','lind'],
    'Age':[25,30,35,95],
    'City':['New York','San Francisco','Los Angeles','Landon']
}

In [14]:
df=pd.DataFrame(data)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3     lind   95         Landon

In [19]:
data_list = [
            ['Alice',	25	,'New York',60000],
            ['Bob'	,30,	'San Francisco',560000],
            ['Charlie'	,35,	'Los Angeles',34000],
            ['lind',	95	,'Landon',000000]
            ]
df2=pd.DataFrame(data_list)
df2

         0   1              2       3
0    Alice  25       New York   60000
1      Bob  30  San Francisco  560000
2  Charlie  35    Los Angeles   34000
3     lind  95         Landon       0

In [30]:
col = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns=col)
df2

      Name  Age           City  Salary
0    Alice   25       New York   60000
1      Bob   30  San Francisco  560000
2  Charlie   35    Los Angeles   34000
3     lind   95         Landon       0

In [31]:
df2['Name']

0      Alice
1        Bob
2    Charlie
3       lind
Name: Name, dtype: object

In [32]:
df2[['Name','City']]

      Name           City
0    Alice       New York
1      Bob  San Francisco
2  Charlie    Los Angeles
3     lind         Landon

In [2]:
import pandas as pd
import numpy as np
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
  dates = pd.date_range("20130101", periods=6)

  dates

  df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

  df

                   A         B         C         D
2013-01-01  0.291288  0.381746  2.381544  1.404587
2013-01-02  2.171966 -0.263132  0.108103 -0.162914
2013-01-03 -1.236642  1.289101  0.040483  0.205412
2013-01-04 -0.380683  0.678349  0.046000 -1.071332
2013-01-05  0.891637 -0.583714 -1.219861 -0.151502
2013-01-06 -0.417858 -2.100084 -0.052660  0.413309

In [11]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\Users\Dell!\Downloads\netflix_titles.csv')   # load data
print(df.head())        # see first 5 rows
print(df.info())        # see column types
print(df.describe())    # see basic statistics

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dell!\\Downloads\\netflix_titles.csv'

In [14]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('https://drive.google.com/drive/home')  # adjust path to where you put it in Drive
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

ParserError: Error tokenizing data. C error: Expected 3648 fields in line 5, saw 6362

In [15]:
from google.colab import files
uploaded = files.upload()   # a "Choose Files" button will appear — click it and select netflix_titles.csv from your PC

import pandas as pd
df = pd.read_csv('netflix_titles.csv')
df.head()

Saving netflix_titles.csv to netflix_titles.csv

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [19]:
df.info()#colum type aur missing values check kro
df.describe()#numeric columns ka summary
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

(8807, 12)

In [20]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [21]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')

In [27]:
most_common_country = df['country'].mode()[0]
df['country'] = df['country'].fillna(most_common_country)

In [28]:
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           4
duration         3
listed_in        0
description      0
dtype: int64